---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    eg:
      - some-file.eg
name: useful
start:
  ctags: -R
  ctags-exclude:
    - perl
    - tmp/
  ctags-excludes:
    perl:
      - blib
      - _build
      - Build
terminals:
  2: []

  3: []

  4: []

